[package]
name = "rubocop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-ruby-parser="3.0.0"
regex = "1"
lazy_static = "1.4.0"
