[package]
name = "doomdooz-wasm"
description = "Ruby linter in webassembly implementing all rubocop features"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
doomdooz-lib = { path = "../doomdooz-lib" }
